"""Initial migration

Revision ID: 033048dc60d6
Revises: 
Create Date: 2026-01-13 06:25:57.917342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '033048dc60d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index('idx_questions_rfp', table_name='rfp_questions')
    op.drop_index('idx_questions_category', table_name='rfp_questions')
    op.drop_table('rfp_questions')
    
    op.drop_index('idx_rfp_status', table_name='rfp_submissions')
    op.drop_index('idx_rfp_deadline', table_name='rfp_submissions')
    op.drop_index('idx_rfp_created', table_name='rfp_submissions')
    op.drop_index('idx_rfp_client', table_name='rfp_submissions')
    op.drop_index('idx_rfp_category', table_name='rfp_submissions')
    op.drop_table('rfp_submissions')
    
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
