"""Add title column to RFPSubmission

Revision ID: e0c9fc94dbcc
Revises: 033048dc60d6
Create Date: 2026-01-13 22:44:36.141867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0c9fc94dbcc'
down_revision: Union[str, Sequence[str], None] = '033048dc60d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_questions_category'), table_name='rfp_questions')
    op.drop_index(op.f('idx_questions_rfp'), table_name='rfp_questions')
    op.drop_table('rfp_questions')
    op.drop_index(op.f('idx_rfp_category'), table_name='rfp_submissions')
    op.drop_index(op.f('idx_rfp_client'), table_name='rfp_submissions')
    op.drop_index(op.f('idx_rfp_created'), table_name='rfp_submissions')
    op.drop_index(op.f('idx_rfp_deadline'), table_name='rfp_submissions')
    op.drop_index(op.f('idx_rfp_status'), table_name='rfp_submissions')
    op.drop_table('rfp_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_submissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_gcs_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget_min', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('budget_max', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('proposal_deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('questions_deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('project_duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('decision_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('analyzed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rfp_submissions_pkey'))
    )
    op.create_index(op.f('idx_rfp_status'), 'rfp_submissions', ['status'], unique=False)
    op.create_index(op.f('idx_rfp_deadline'), 'rfp_submissions', ['proposal_deadline'], unique=False)
    op.create_index(op.f('idx_rfp_created'), 'rfp_submissions', ['created_at'], unique=False)
    op.create_index(op.f('idx_rfp_client'), 'rfp_submissions', ['client_name'], unique=False)
    op.create_index(op.f('idx_rfp_category'), 'rfp_submissions', ['category'], unique=False)
    op.create_table('rfp_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rfp_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('why_important', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_answered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp_submissions.id'], name=op.f('rfp_questions_rfp_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rfp_questions_pkey'))
    )
    op.create_index(op.f('idx_questions_rfp'), 'rfp_questions', ['rfp_id'], unique=False)
    op.create_index(op.f('idx_questions_category'), 'rfp_questions', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
