"""Recreate tables migration

Revision ID: f1e2d3c4b5a6
Revises: 033048dc60d6
Create Date: 2024-01-14 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1e2d3c4b5a6'
down_revision: Union[str, None] = '033048dc60d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    
    # Try to clean up if partial tables exist (optional, safer to rely on 'if not exists' implicitly via clean state, 
    # but here we assume tables are missing as per user report).
    
    # Create users table
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Create rfp_submissions table
    op.create_table('rfp_submissions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_gcs_path', sa.String(length=500), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('client_name', sa.String(length=255), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('budget_min', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('budget_max', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=20), nullable=True),
        sa.Column('proposal_deadline', sa.Date(), nullable=True),
        sa.Column('questions_deadline', sa.Date(), nullable=True),
        sa.Column('project_duration', sa.String(length=100), nullable=True),
        sa.Column('confidence_score', sa.Integer(), nullable=True),
        sa.Column('recommendation', sa.String(length=20), nullable=True),
        sa.Column('decision', sa.String(length=10), nullable=True),
        sa.Column('decision_reason', sa.Text(), nullable=True),
        sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rfp_category', 'rfp_submissions', ['category'], unique=False)
    op.create_index('idx_rfp_client', 'rfp_submissions', ['client_name'], unique=False)
    op.create_index('idx_rfp_created', 'rfp_submissions', ['created_at'], unique=False)
    op.create_index('idx_rfp_deadline', 'rfp_submissions', ['proposal_deadline'], unique=False)
    op.create_index('idx_rfp_status', 'rfp_submissions', ['status'], unique=False)

    # Create rfp_questions table
    op.create_table('rfp_questions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('rfp_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('priority', sa.String(length=10), nullable=True),
        sa.Column('context', sa.Text(), nullable=True),
        sa.Column('why_important', sa.Text(), nullable=True),
        sa.Column('is_answered', sa.Boolean(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['rfp_id'], ['rfp_submissions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_category', 'rfp_questions', ['category'], unique=False)
    op.create_index('idx_questions_rfp', 'rfp_questions', ['rfp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index('idx_questions_rfp', table_name='rfp_questions')
    op.drop_index('idx_questions_category', table_name='rfp_questions')
    op.drop_table('rfp_questions')
    
    op.drop_index('idx_rfp_status', table_name='rfp_submissions')
    op.drop_index('idx_rfp_deadline', table_name='rfp_submissions')
    op.drop_index('idx_rfp_created', table_name='rfp_submissions')
    op.drop_index('idx_rfp_client', table_name='rfp_submissions')
    op.drop_index('idx_rfp_category', table_name='rfp_submissions')
    op.drop_table('rfp_submissions')
    
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
